### ISSUE TITLE
Cannot await without a Fiber

### ISSUE THREAD

**Issue by crapthings** [meteor/promise#21]
Cannot await without a Fiber

require('meteor-promise').makeCompatible(Promise, require('fibers'))

node v8.9.4
"fibers": "^2.0.0",
"meteor-promise": "^0.8.6",

**Comment by crapthings** [comment]
@benjamn 
```js
AssertionError [ERR_ASSERTION]: Cannot await without a Fiber
    at awaitPromise (/Users/monsterstep/dev/cube-patch/services/cube-report-service/node_modules/meteor-promise/promise_server.js:75:12)
    at Function.Promise.await (/Users/monsterstep/dev/cube-patch/services/cube-report-service/node_modules/meteor-promise/promise_server.js:56:12)
    at Object.<anonymous> (/Users/monsterstep/dev/cube-patch/services/cube-report-service/index.js:10:29)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
AssertionError [ERR_ASSERTION]: Cannot await without a Fiber
    at awaitPromise (/Users/monsterstep/dev/cube-patch/services/cube-report-service/node_modules/meteor-promise/promise_server.js:75:12)
    at Function.Promise.await (/Users/monsterstep/dev/cube-patch/services/cube-report-service/node_modules/meteor-promise/promise_server.js:56:12)
    at Object.<anonymous> (/Users/monsterstep/dev/cube-patch/services/cube-report-service/index.js:10:29)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
