### ISSUE TITLE
Promise.await error in meteor-cordova app development

### ISSUE THREAD

**Issue by physicsgirl** [meteor/promise#23]
I tried getting my app to run via cmd after installing emulator and all the packages and jdk-

    C:\Users\DELL>cd Coolio

    C:\Users\DELL\Coolio>meteor run android

and this is the error that it throws-

    "C:\Users\DELL\AppData\Local\.meteor\packages\meteor-tool\1.7.0_3\mt- os.windows.x86_32\dev_bundle\lib\node_modules\meteor- 
    promise\promise_server.js:218
      throw error;
      ^
    undefined
     => awaited here:
    at Function.Promise.await (C:\Users\DELL\AppData\Local\.meteor\packages\meteor-tool\1.7.0_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:56:12)
    at Promise.asyncApply (C:\tools\cordova\run-targets.js:111:5)
    at C:\Users\DELL\AppData\Local\.meteor\packages\meteor-tool\1.7.0_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\fiber_pool.js:43:40
     => awaited here:
    at Function.Promise.await (C:\Users\DELL\AppData\Local\.meteor\packages\meteor-tool\1.7.0_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:56:12)
    at buildmessage.capture (C:\tools\cordova\runner.js:98:9)
    at C:\tools\utils\buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at CordovaRunner.startRunTargets (C:\tools\cordova\runner.js:97:37)
    at AppRunner._runOnce (C:\tools\runners\run-app.js:767:21)
    at AppRunner._fiber (C:\tools\runners\run-app.js:880:28)
    at C:\tools\runners\run-app.js:408:12"

Please tell me how to fix it.

**Comment by KonVas** [comment]
I think I am having the same exact problem, is there any workaround currently?

**Comment by physicsgirl** [comment]
I did, yeah, got a workaround. I forgot what it was though. I'll be working
again on it in Dec and I'll let you know when I come across it.

**Comment by aaronsmulktis** [comment]
I'm having the exact same issue with the same error. I've tried `meteor reset`, I've tried creating a new project, I've tried installing specific older releases of Meteor (v1.4 to 2.0), nothing is working :( I can't get any Meteor app to start at all, old or new.
